### ISSUE TITLE
--up option does not work

### ISSUE THREAD

**Issue by vizmi** [calvinmetcalf/copyfiles#2] opened 2015-04-19 19:16 UTC
This command works:
`copyfiles src/*.html test`

but this does not:
`copyfiles -u 1 src/*.html test`

the exception is:
`{ [Error: EISDIR, open 'C:\Users\me\project\test']
  errno: -4068,
  code: 'EISDIR',
  path: ''C:\\Users\\me\\project\\test'' }`

As far as I can tell EISDIR error code means the system got a directory but expected something else (file?).

**Comment by calvinmetcalf** [comment] 2015-04-19 22:45
Hm will look into it

**Comment by calvinmetcalf** [comment] 2015-04-20 12:19
try

```js
copyfiles -u 1 src/*.html test
```

you have a folder in there with html in it's name add the dot so it treats it as an extension

**Comment by vizmi** [comment] 2015-04-20 21:49
No, I have found it: paths emitted by glob module needs to be normalized before splitting them. Check out my pull request: [pull request](https://github.com/calvinmetcalf/copyfiles/pull/3)

**Comment by vizmi** [comment] 2015-04-21 02:16
While at it I found another problem: sub-directories created as files, files underneath the source sub-directory will fail with "Not a directory" error. I have a fix for that too, if you are interested.

**Comment by calvinmetcalf** [comment] 2015-04-21 13:09
I'm not sure it's the normalize issue because I was able to reproduce the issue on a mac

**Comment by vizmi** [comment] 2015-04-21 14:25
I am fine with any solution.
At this point 4 of your tape test cases fails for me. The ones with -u option.

**Comment by vizmi** [comment] 2015-04-21 15:13
Also can you please consider using the up = 1 as the default value? Usually when I copy file from a folder to another I don't want to see the source folder under the destination, only the files/subfolders.

**Comment by calvinmetcalf** [comment] 2015-04-22 17:54
to avoid a breaking change we can have it do a second command that defaults to up=1 maybe `copyup`

**Comment by calvinmetcalf** [comment] 2015-04-22 18:14
see #5 for the version with --up=1, otherwise I think your issue is fixed in the newer version please reopen if it isn't

**Closed by calvinmetcalf** 2015-04-22 18:14 UTC
